In [1]:
import numpy as np

In [2]:
a=np.array([8,6,5])

In [56]:
b=np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])

In [5]:
b.shape

(4, 3)

In [12]:
c=np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])

In [13]:
c.shape

(3, 3, 2)

In [8]:
b

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [14]:
c

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [15]:
b[1,0:3:1]

array([9, 3, 5])

In [18]:
b[0:4:1,2:]

array([[ 4],
       [ 5],
       [17],
       [ 8]])

In [19]:
c[0,0,0]

4

In [30]:
c[0:,0:,0:2]

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [25]:
c[:,2]

array([[  7,  71],
       [  5,  51],
       [ 13, 131]])

In [29]:
b[:,2:].shape

(4, 1)

In [31]:
b[:,-1:]

array([[ 4],
       [ 5],
       [17],
       [ 8]])

In [39]:
c[1:3,1:3,0]

array([[ 1,  5],
       [ 9, 13]])

In [42]:
c[1:,1:3,1]

array([[ 11,  51],
       [ 91, 131]])

In [43]:
c[1:3,0:1:3]

array([[[ 3, 31]],

       [[ 6, 61]]])

In [44]:
x=[3,5,9]
#x+5 list can be added with an integer but we can do it with array

TypeError: can only concatenate list (not "int") to list

In [45]:
a+5

array([13, 11, 10])

In [46]:
a[0]*2

16

In [47]:
a[0]

8

In [48]:
a[0]=13

In [49]:
a

array([13,  6,  5])

In [57]:
b[0,:]=[30,40,50]

In [58]:
b

array([[30, 40, 50],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [68]:
b[:,-2]=[60,70,80,90]

In [63]:
b

array([[30, 60, 50],
       [ 9, 70,  5],
       [11, 80, 17],
       [19, 90,  8]])

In [69]:
b[4,:]=[1,1,1]   #we cant add a row directly in an array ,for this we will use append funcn

IndexError: index 4 is out of bounds for axis 0 with size 4

In [70]:
np.append(b,[[1,1,1]],axis=0)  #axis=0 to add a row

array([[30, 60, 50],
       [ 9, 70,  5],
       [11, 80, 17],
       [19, 90,  8],
       [ 1,  1,  1]])

In [76]:
np.append(b,[[2],[4],[6],[8]],axis=1)

array([[30, 60, 50,  2],
       [ 9, 70,  5,  4],
       [11, 80, 17,  6],
       [19, 90,  8,  8]])

In [78]:
np.delete(b,1,0)

array([[30, 60, 50],
       [11, 80, 17],
       [19, 90,  8]])

In [80]:
np.delete(b,1)

array([30, 50,  9, 70,  5, 11, 80, 17, 19, 90,  8])

In [81]:
b.shape

(4, 3)

In [82]:
b.reshape(6,2)

array([[30, 60],
       [50,  9],
       [70,  5],
       [11, 80],
       [17, 19],
       [90,  8]])

In [84]:
b.reshape(2,2,3)

array([[[30, 60, 50],
        [ 9, 70,  5]],

       [[11, 80, 17],
        [19, 90,  8]]])

In [85]:
a.dtype

dtype('int32')

In [90]:
a1=np.array([3.5,1,4,6])
a1

array([3.5, 1. , 4. , 6. ])

In [91]:
a1.dtype

dtype('float64')

In [92]:
a1.astype('uint16')

array([3, 1, 4, 6], dtype=uint16)

In [93]:
a1

array([3.5, 1. , 4. , 6. ])

In [97]:
b1=a1.astype(int)

In [98]:
b1

array([3, 1, 4, 6])

In [99]:
a1

array([3.5, 1. , 4. , 6. ])

In [100]:
b.sum()

14

In [104]:
b.sum(axis=0)

14

In [105]:
#creating array
#1.np.array()
#2. np.ones()
#np.zeros()
# 4 np.arange()
#np.linspace()
#np.random

In [106]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [107]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [108]:
np.random.randint(1,15,[3,4])

array([[ 8,  4,  6, 10],
       [13,  8, 13,  1],
       [11, 12, 14,  3]])

In [2]:
import numpy as np

In [3]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
np.linspace(1,10,10,dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(1,11,1,dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.random.randint(1,6,1)

array([2])

In [11]:
np.random.randint(1,6,1)  #every time it runs gives random number array   syntax(start,end,how many)

array([3])

In [12]:
np.random.randint(1,6,[4,3,2])

array([[[5, 3],
        [3, 2],
        [4, 1]],

       [[2, 2],
        [4, 4],
        [1, 2]],

       [[1, 2],
        [5, 1],
        [4, 5]],

       [[2, 2],
        [2, 4],
        [1, 1]]])

In [13]:
np.random.randint(11,600,[4,3])

array([[342, 571, 529],
       [239, 400, 171],
       [187, 214, 301],
       [ 12, 323, 203]])

In [15]:
np.random.seed(10)             #the seed stablises the randomness,here each time we will run the values doesn't change
np.random.randint(31,6000,[4,3])



array([[1320, 4654, 1375],
       [3472, 1211, 2040],
       [4860, 1551, 1980],
       [2073, 1063, 1128]])

In [16]:
np.random.rand(3,4)    #it generates numbers less than 1

array([[0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578]])

In [17]:
r=np.loadtxt('somedata.txt',dtype=str)               # to access the file that have been created in the samne folder so numpy loads that file
r

array(['hi', 'this', 'is', 'a', 'new', 'file'], dtype='<U4')

In [18]:
s=np.loadtxt('moredata.txt')

In [19]:
s

array([[45., 66., 77., 34.],
       [12., 15., 10.,  8.]])

In [20]:
p=np.random.rand(3,4) 
p

array([[0.54254437, 0.14217005, 0.37334076, 0.67413362],
       [0.44183317, 0.43401399, 0.61776698, 0.51313824],
       [0.65039718, 0.60103895, 0.8052232 , 0.52164715]])

In [22]:
np.savetxt('new.txt',p,delimiter=',')             #the savetxt exports numpy data into a file,syntax(file name,variable name,how to separate data)