In [1]:
import numpy    #introduced in python to as numpyndarray to have funcn like array purpose is to create homogenous collection

In [ ]:
#keywords from , import, as

In [2]:
import my_file

In [3]:
my_file.abc()

Good message


In [4]:
import keyboard

ModuleNotFoundError: No module named 'keyboard'

In [5]:
import keyword

In [6]:
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [8]:
import keyword as kw
kw.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [14]:
from keyword import kwlist,iskeyword as isk
kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [13]:
iskeyword('if')

True

In [15]:
isk('else')

True

In [17]:
import numpy as np

In [18]:
a=np.array([])
a

array([], dtype=float64)

In [19]:
b=np.array([3,4,5,6,7])
b

array([3, 4, 5, 6, 7])

In [20]:
len(a)

0

In [21]:
len(b)

5

In [22]:
a.dtype

dtype('float64')

In [23]:
b.dtype

dtype('int32')

In [24]:
b.shape

(5,)

In [25]:
b.size

5

In [27]:
a.ndim

1

In [28]:
b.ndim

1

In [29]:
type(a)

numpy.ndarray

In [30]:
c=np.array([[2,3,4],[5,6,7],[8,9,10],[11,12,13]])     #the green bracket having no of comma separated vlues gives rows and the values inside brown brac gives columns
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [31]:
c.shape

(4, 3)

In [32]:
d=np.array([[[2,20],[3,30],[4,40]],[[5,50],[6,60],[7,70]],[[8,80],[9,90],[10,100]],[[11,110],[12,120],[13,130]]]) 
d

array([[[  2,  20],
        [  3,  30],
        [  4,  40]],

       [[  5,  50],
        [  6,  60],
        [  7,  70]],

       [[  8,  80],
        [  9,  90],
        [ 10, 100]],

       [[ 11, 110],
        [ 12, 120],
        [ 13, 130]]])

In [33]:
d.shape

(4, 3, 2)

In [34]:
c.sum(axis=1)

array([ 9, 18, 27, 36])

In [35]:
c[0:2,-1]    #subscripting

array([4, 7])

In [36]:
c[0:2,2:]

array([[4],
       [7]])

In [37]:
c[0:2,-1:]

array([[4],
       [7]])